import streamlit as st
import sys
import pathlib
import pandas as pd

# --- Path setup ---
sys.path.append(str(pathlib.Path(__file__).parent.parent))
from agents.orchestrator import Orchestrator

# --- Page Configuration ---
st.set_page_config(page_title="AI Consultant", layout="wide")
st.title("🤖 Your Personal AI Investment Consultant")
st.markdown("Describe your financial goals, and our AI system will automatically discover and analyze top market opportunities to build you a personalized plan.")

# --- Load the Orchestrator ---
@st.cache_resource
def load_orchestrator():
    config_path = "quant-company-insights-agent/config.yaml"
    return Orchestrator.from_file(config_path)

orchestrator = load_orchestrator()

# --- User Profile & Analysis Input ---
with st.sidebar:
    st.header("👤 Your Profile")
    
    user_profile_text = st.text_area(
        "Describe your financial goals and situation",
        height=150,
        value="I am a salaried professional in my late 20s, looking for long-term growth for my savings. I have a medium risk tolerance.",
        help="Describe your profession, age, income, investment goals (e.g., retirement, buying a house), and risk tolerance."
    )
    
    st.markdown("---")
    st.header("🔍 Analysis Parameters")

    market = st.radio("Select Market to Analyze", ["USA", "India"], horizontal=True)
    
    run_button = st.button("💡 Discover & Generate My Plan", use_container_width=True)

# --- Main Panel Execution ---
if run_button:
    if not orchestrator.llm_agent.ollama_available:
        st.error("Ollama server not detected. Please ensure Ollama is running on your machine to use the AI Consultant.")
    elif not user_profile_text:
        st.warning("Please describe your financial profile in the sidebar text area.")
    else:
        st.header("Here is Your Personalized & Synthesized Investment Plan")
        st.info("This report was generated by automatically discovering the top-performing sector and stock, running a full analysis, and synthesizing recommendations from Llama 3 and Mistral.")

        with st.spinner("Performing automated discovery and analysis... This may take a few minutes."):
            final_recommendation = orchestrator.run_automated_ai_discovery_and_plan(
                user_profile_text=user_profile_text,
                market=market.lower()
            )
            
            st.markdown(final_recommendation)
else:
    st.info("Please describe your profile in the sidebar, select a market, and click 'Discover & Generate My Plan' to get started.")
# import streamlit as st
# import sys
# import pathlib
# import json
# import pandas as pd # Add pandas for date calculation

# # --- Path setup ---
# sys.path.append(str(pathlib.Path(__file__).parent.parent))
# from agents.orchestrator import Orchestrator

# # --- Page Configuration ---
# st.set_page_config(page_title="AI Consultant", layout="wide")
# st.title("🤖 Your Personal AI Investment Consultant")
# st.markdown("Get a comprehensive, synthesized investment plan from multiple AI analysts based on a full market and stock analysis.")

# # --- Load the Orchestrator ---
# @st.cache_resource
# def load_orchestrator():
#     config_path = "quant-company-insights-agent/config.yaml"
#     print("--- LOADING ORCHESTRATOR FOR AI CONSULTANT PAGE ---")
#     return Orchestrator.from_file(config_path)

# orchestrator = load_orchestrator()

# # --- User Profile & Analysis Input ---
# with st.sidebar:
#     st.header("👤 Your Profile")
    
#     profession = st.selectbox(
#         "Your Profession", 
#         ["Student", "Salaried Professional", "Business Owner"]
#     )
#     # --- NEW: Annual Income Input ---
#     income = st.number_input("Your Annual Income (USD)", min_value=0, value=75000, step=5000)
    
#     goal = st.selectbox(
#         "Your Primary Goal", 
#         ["Maximum Savings (Long-Term Growth)", "Steady Income (Dividends)", "Funding a Startup (Aggressive Growth)"]
#     )
#     risk = st.selectbox(
#         "Your Risk Tolerance", 
#         ["Low", "Medium", "High (Aggressive)"]
#     )
    
#     st.markdown("---")
#     st.header("🔍 Analysis Parameters")

#     market = st.radio("Select Market", ["USA", "India"], horizontal=True)
    
#     # --- NEW: Ticker input for Deep Dive ---
#     analysis_ticker = st.text_input("Stock Ticker to Analyze", "AAPL" if market == "USA" else "RELIANCE")
    
#     # --- NEW: Strategy selection for Combination Builder ---
#     available_strategies = sorted(list(orchestrator.short_term_modules.keys()))
#     default_strategies = ["Momentum", "Mean Reversion (Bollinger Bands)"] if "Momentum" in available_strategies else available_strategies[:2]
#     portfolio_strategies = st.multiselect(
#         "Strategies to Backtest", 
#         options=available_strategies, 
#         default=default_strategies
#     )
    
#     run_button = st.button("💡 Generate My Plan", use_container_width=True)

# # --- Main Panel Execution ---
# if run_button:
#     # Check if the Ollama server is actually available
#     if not orchestrator.llm_agent.ollama_available:
#         st.error("Ollama server not detected. Please ensure Ollama is running on your machine to use the AI Consultant.")
#     elif not analysis_ticker or not portfolio_strategies:
#         st.warning("Please provide a ticker to analyze and select at least one strategy.")
#     else:
#         st.header("Here is Your Personalized & Synthesized Investment Plan")
#         st.info("This report was generated by running a full analysis, getting opinions from both **Llama 3** and **Mistral**, and having a senior AI analyst synthesize the results into a single plan.")

#         # 1. Assemble the complete user profile
#         user_profile = {
#             "profession": profession,
#             "annual_income": income,
#             "goal": goal, 
#             "risk": risk
#         }
        
#         # Define a date range for the analysis (e.g., past 2 years)
#         end_date_str = pd.Timestamp.now().strftime('%Y-%m-%d')
#         start_date_str = (pd.Timestamp.now() - pd.DateOffset(years=2)).strftime('%Y-%m-%d')
        
#         with st.spinner("Performing comprehensive analysis and consulting with AI analysts... This may take a few minutes."):
#             # 2. Call the new Orchestrator method
#             final_recommendation = orchestrator.run_comprehensive_ai_analysis(
#                 user_profile=user_profile,
#                 analysis_ticker=analysis_ticker,
#                 portfolio_strategies=portfolio_strategies,
#                 market=market,
#                 start_date=start_date_str,
#                 end_date=end_date_str
#             )
            
#             # 3. Display the final result
#             st.markdown(final_recommendation)

# else:
#     st.info("Please configure your profile and analysis parameters in the sidebar, then click 'Generate My Plan' to get started.")

# import streamlit as st
# import sys
# import pathlib
# import json

# # --- Path setup to allow importing from the 'agents' directory ---
# sys.path.append(str(pathlib.Path(__file__).parent.parent))
# from agents.orchestrator import Orchestrator

# # --- Page Configuration ---
# st.set_page_config(page_title="AI Consultant", layout="wide")
# st.title("🤖 Your Personal AI Investment Consultant")
# st.markdown("Get a personalized investment plan based on your profile and live market data.")

# # --- Cached Functions for Performance ---

# @st.cache_resource
# def load_orchestrator():
#     """
#     Loads the orchestrator once and caches the resource for the entire session.
#     """
#     config_path = "quant-company-insights-agent/config.yaml"
#     print("--- LOADING ORCHESTRATOR (this should only run once) ---")
#     return Orchestrator.from_file(config_path)

# @st.cache_data(ttl=600) # Cache the AI's response for 10 minutes
# def get_cached_recommendation(_orchestrator, user_profile_json: str):
#     """
#     This wrapper function allows Streamlit to cache the AI's response.
#     We pass the user_profile as a JSON string to make it hashable for the cache.
#     The underscore on _orchestrator tells Streamlit not to hash the complex object.
#     """
#     print(f"--- CACHE MISS: Calling real get_personalized_recommendation for profile: {user_profile_json} ---")
#     # Convert the JSON string back to a dictionary before passing to the orchestrator
#     user_profile = json.loads(user_profile_json)
#     return _orchestrator.get_personalized_recommendation(user_profile)

# # --- Load the Orchestrator ---
# orchestrator = load_orchestrator()

# # --- Sidebar for User Input ---
# # This section is now defined only ONCE.
# with st.sidebar:
#     st.header("👤 Tell Us About Yourself")
    
#     profession = st.selectbox(
#         "Your Profession", 
#         ["Student", "Salaried Professional", "Business Owner"]
#     )
#     goal = st.selectbox(
#         "Your Primary Goal", 
#         ["Maximum Savings (Long-Term Growth)", "Steady Income (Dividends)", "Funding a Startup (Aggressive Growth)"]
#     )
#     risk = st.selectbox(
#         "Your Risk Tolerance", 
#         ["Low", "Medium", "High (Aggressive)"]
#     )
#     horizon = st.selectbox(
#         "Your Time Horizon", 
#         ["Short-Term (< 2 years)", "Medium-Term (2-5 years)", "Long-Term (5+ years)"]
#     )
    
#     # The "Generate My Plan" button is also here.
#     run_button = st.button("💡 Generate My Plan", use_container_width=True)


# # --- Main Panel Execution ---
# # This block runs ONLY when the button in the sidebar is clicked.
# if run_button:
#     st.header("Here is Your Personalized Investment Plan")
    
#     # 1. Assemble the user profile into a dictionary
#     user_profile = {
#         "profession": profession, 
#         "goal": goal, 
#         "risk": risk, 
#         "horizon": horizon
#     }
    
#     with st.spinner("Your AI consultant is analyzing the markets and tailoring a plan for you..."):
#         # 2. Convert profile to a JSON string to make it hashable for caching
#         user_profile_json_string = json.dumps(user_profile, sort_keys=True)
        
#         # 3. Call the cached function with the orchestrator and the hashable profile
#         recommendation_markdown = get_cached_recommendation(orchestrator, user_profile_json_string)
        
#         # 4. Display the result
#         st.markdown(recommendation_markdown)

# else:
#     st.info("Please configure your profile in the sidebar and click 'Generate My Plan' to get started.")